# Numpy

## Importing Libraries

In [1]:
import numpy as np

## Array Creation

In [2]:
arr = np.array([1,2,3,4,5,6])

print(arr)

[1 2 3 4 5 6]


In [3]:
zero = np.zeros((10,2))
zero1 = np.zeros(11)
print(zero)
print(zero1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
np1 = np.ones(10)
np2 = np.ones((2,10))
print(np1)
print(np2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [5]:
range_arr = np.arange(2,10,1)
print(range_arr)

[2 3 4 5 6 7 8 9]


In [6]:
shape = np.shape([1,2,3,4,5,6,7,8,9])
print(shape)

(9,)


In [7]:
print(arr.dtype)

int32


## Array Manipulation

In [8]:
np1 = np.array([1,2,3,4,5,6])
reshaped = np1.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [9]:
np1 = np.array([[1,2,3],[7,8,9]])
np2 = np.array([[4,5,6]])

concatenated = np.concatenate((np1, np2), axis = 0)
print(concatenated)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [10]:
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
vstacked = np.vstack((np1,np2))
print(vstacked)

[[1 2 3]
 [4 5 6]]


In [11]:
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
vstacked = np.hstack((np1,np2))
print(vstacked)

[1 2 3 4 5 6]


In [12]:
np1 = np.array([1,2,3,4,5,6,7,8,9])
split_arr = np.split(np1,3)
print(split_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [13]:
matrix = np.array([[1,2,3],[4,5,6]])

transposed = np.transpose(matrix)
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
arr = np.array([1,2,3,4])

resized = np.resize(arr,(3,3))
print(resized)

[[1 2 3]
 [4 1 2]
 [3 4 1]]


## Statistical Analysis

In [15]:
np1 = np.array([1,2,3,4,5])

print(sum(np1))
print(np.mean(np1))
print(np.median(np1))
print(np.std(np1))
print(np.var(np1))
print(np.cov(np1))
print(np.corrcoef(np1))
print(min(np1))
print(max(np1))

15
3.0
3.0
1.4142135623730951
2.0
2.5
1.0
1
5


In [16]:
random = np.random.rand(5)
print(random)

[0.94293853 0.76420718 0.90958723 0.00148211 0.54462148]


In [17]:
random = np.random.randn(5)
print(random)

[-1.71845386  0.49178488  0.80002271  0.66441727 -0.04587789]


In [18]:
arr = np.array([1, 2, 1, 2, 3, 3, 3, 4, 5])

hist, bins = np.histogram(arr, bins = 5)
print(hist)
print(bins)

[2 2 3 1 1]
[1.  1.8 2.6 3.4 4.2 5. ]


## Indexing & Filtering

In [19]:
#extract, Where, isnan, sort, unique

arr = np.array([1,2,3,4,5,6,7,8,9])
condition = arr % 2 == 0
extraced = np.extract(condition, arr)
print(extraced)

arr = np.array([1,2,3,4,5,6,7,8,9])
condition = arr % 2 == 1
extracted = np.extract(condition, arr)
print(extracted)


[2 4 6 8]
[1 3 5 7 9]


In [20]:
arr = np.array([1,2,3,4,5,6])
condition = np.where(arr > 3, 9 ,arr)
print(condition)
#print(arr[condition])

arr = np.array([10, 20, 30, 40, 50])
modified_arr = np.where(arr > 25, 100, arr)  # Replace values > 25 with 100
print(modified_arr)  # Output: [10 20 100 100 100]

[1 2 3 9 9 9]
[ 10  20 100 100 100]


In [21]:
arr = np.array([1,2,np.nan, 4, np.nan])
print(np.isnan(arr))

[False False  True False  True]


In [22]:
arr = np.array([1,3,5,6,2,6,9,1,2])
condition = np.sort(arr)
print(condition)

[1 1 2 2 3 5 6 6 9]


In [23]:
arr = np.array([1,1,3,4,2,3,1,4,2,1])
condition = np.unique(arr)
print(condition)

[1 2 3 4]


## File I/O

In [24]:
arr = np.array([1,2,3,4,5])

np.save('my_list.npy', arr)


In [25]:
loading = np.load('my_list.npy')
print(loading)

[1 2 3 4 5]
